### PR TITLE
Added travis test support

### PR DESCRIPTION
**Pull request by markmcd**
May not work yet - making sure the config file works first.

### CODE REVIEW

**Comment by broady** [comment]
oh, sick! this is great.

merge at will

**Comment by markmcd** [comment]
Got it working now (i.e. failing correctly on PointQuadTreeTest) - but there's some issue with the testIcon test. I suspect something's up with the emulator and Google Play Services.

```
com.google.maps.android.geojson.GeoJsonPointStyleTest > testIcon[test(AVD) - 4.4.2] FAILED 
	java.lang.NullPointerException: IBitmapDescriptorFactory is not initialized
	at com.google.android.gms.common.internal.zzx.zzb(Unknown Source)
```

**Comment by barbeau** [comment]
Fully working Travis build is available at:
https://github.com/googlemaps/android-maps-utils/pull/209

**Comment by barbeau** [comment]
This PR can be closed now that https://github.com/googlemaps/android-maps-utils/pull/209 is merged.

**Pull request closed without merging**
