### PR TITLE
Handle altitudes and parse Track and MultiTrack objects

### PR DESCRIPTION
**Pull request by noberasco**
This pull request extends the KML file parsing capabilities by:
- adding support for altitudes to KmlPoint and KmlMultiline objects
- adding support for <Track> and <MultiTrack> geometries in KML files (including, of course, altitudes)

The change is backwards compatible: features have been added to existing objects but their pre-existing structure has otherwise been left untouched.

The new KmlTrack object inherits from KmlLineString.
The new KmlMultiTrack object inherits from KmlMultiGeometry and contains a list of KmlTrack objects.

Both objects, once parsed, can be rendered without further hassle with the existing infrastructure.

On an unrelated note, is there any particular reason why KmlParser is package private? I'm using this library to parse data from KML files and load it into my own application, which has its own storage model for tracks, routes and waypoints. I suspect that many applications could benefit from the robust KML parsing that this library offers, but like mine have uses for the parsed data other than immediate rendering on a MapView...

### CODE REVIEW

**Comment by noberasco** [comment]
The two features (altitude support and Track/MultiTrack support) can also be added independently. I found it more convent to include them in a single pull request as I coded Track/MultiTrack with altitude support already built in, but I can split them into separate pull requests if you prefer. This would mean creating one for, say, Track/MultiTrack support and, once it is merged, another one for altitudes. Or vice versa.

**Comment by barbeau** [comment]
Thanks @noberasco!  Could you please add unit tests here as well?

**Comment by noberasco** [comment]
Sure @barbeau, I'll add some unit tests as soon as work allows me :-)

**Comment by noberasco** [comment]
As requested, I added several unit tests for the new features.
@barbeau, let me know if other changes are required ;-)

**Comment by noberasco** [comment]
Any feedback on this one?
It has been sitting idle for some time now...

**Comment by barbeau** [comment]
@noberasco Thanks for adding the unit tests!  Reviewing this has been on my TODO list but I'm fairly backlogged at the moment.

**Comment by noberasco** [comment]
New commit: I added support for altitudes to GeoJsonLineString and GeoJsonPoint objects.
I'll add unit tests for these as well.

**Comment by noberasco** [comment]
As promised (but mightily late) I added unit tests for altitude support in GeoJsonLineString and GeoJsonPoint.

**Comment by noberasco** [comment]
@barbeau is there hope for this pull request to be integrated, yet? ;-)

**Comment by noberasco** [comment]
This is depressing.

Instead of simply making the modifications I needed for my project, I took the extra effort required to make them polished enough for inclusion. Then, at developer request, I spent even more time creating unit tests.

What do I get in return? Seven months of silence.

I can understand that you may not be interested in my changes. Actually, that would be perfectly acceptable. But asking people to spend time, then ignoring them for months is distasteful.

**Comment by barbeau** [comment]
@noberasco Your efforts to get things in good shape for merge are appreciated!  I understand your frustration, I've been there too. I'm a volunteer contributor to this project in my free time (of which there hasn't been much lately), hence delays in my review.  My comments above are aimed at trying to get things in shape so they can be easily reviewed/merged as project resources allow.

**Comment by noberasco** [comment]
As a developer I have precious little time myself, so I understand that.
Its the 'zero communication' part that frustrates me.
Anyway, I rebased my patch against your current master and retested it, still looks good on my part.
If ever this gets merged, there are other contributions that I would like to propose later on ;-)

**Comment by stephenmcd** [comment]
Merged now! Thanks a lot and sorry about the delay.

**Pull request merged**
