### PR TITLE
Add Douglas-Peucker algorithm

### PR DESCRIPTION
**Pull request by pvllnspk**

### CODE REVIEW

**Comment by broady** [comment]
Cool! Thanks. A few things:

1. Have you signed the Google CLA?
2. Does this work for very complex paths? Will you see a `StackOverflowError`?
3. Can you add some tests?

**Comment by barbeau** [comment]
@pvllnspk Any plans to update this PR per @broady's feedback so it could be merged?

I'd also like to see Douglas-Peucker be part of this library, and ran across this PR.  My original plan was to look at bringing over the [MyTracks implementation of Douglas-Peucker](https://code.google.com/p/mytracks/source/browse/MyTracks/src/com/google/android/apps/mytracks/util/LocationUtils.java#81) - this is already licensed under Apache (from Google) and does include [some tests](https://code.google.com/p/mytracks/source/browse/MyTracksTest/src/com/google/android/apps/mytracks/io/sendtogoogle/SendToGoogleUtilsTest.java#70) (indirectly, although I believe they could be pulled out without too much effort).

If there aren't plans to move forward with this PR, I may look at opening a new one based on the MyTracks implementation.

**Comment by broady** [comment]
@barbeau one based off MyTracks would be excellent.

**Comment by barbeau** [comment]
@broady Given that this library uses `LatLng` extensively, I assume you'd want a Douglas-Peucker implementation to use the same (vs. `Location`)?

**Comment by broady** [comment]
Yes, that makes sense.

**Comment by barbeau** [comment]
Cool!  Ok, started a port of the MyTracks code here:
https://github.com/barbeau/android-maps-utils/tree/barbeau-douglas-peucker

Commit:
https://github.com/barbeau/android-maps-utils/commit/c9bcce63ec571420e1b4b29ef4c850b02067ea43

Douglas-Peucker decimation algorithm is ported - only modifications to the algorithm itself are to use `LatLng` instead of `Location`, and use the `SphericalUtil.computeDistanceBetween()` in this library instead of the MyTracks distance calculation utility method.

From a closer look at the MyTracks test, though, it's not doing what I assumed it was doing.  I'll work on a better test case (I'm thinking to just simplify the already included encoded polyline, and test that the results match up) and then clean this up to submit as a new PR.

**Comment by broady** [comment]
awesome, nice work!

can you add in a link that references the MyTracks code?

might also need to check the license it is released under.

**Comment by barbeau** [comment]
@broady Thanks!  Yes, link to MyTracks code is in the commit summary.  I'll clean that up a bit when I rebase for the PR.  MyTracks is under Apache 2.0, so it should be clean.  On a related note, I've signed the Google CLA for other Google Github projects, so I think that applies to this project too?

Also, is there an Android Studio code template for this project?

I'm using the default Android template in AS, but I have to keep fighting AS from modifying white-space in this project.  You'll notice in the above commit some whitespace changes snuck in when I committed.  Not sure how particular you are about PRs including unrelated whitespace changes.

**Comment by barbeau** [comment]
PR for MyTracks port of Douglas-Peucker, including tests and demo activity, is now open at https://github.com/googlemaps/android-maps-utils/pull/201.

**Pull request closed without merging**
