### PR TITLE
Fix #575 - Change Travis config, use matrix of API emulators

### LINKED ISSUE #575: Travis emulator executions occasionally fail
This is a follow-on to https://github.com/googlemaps/android-maps-utils/issues/371, which was fixed in PR https://github.com/googlemaps/android-maps-utils/pull/573 - after this PR the emulator is running again on Travis and executing the instrumented unit tests.

However, we're still seeing occasional failures on Travis which appear to be related to adb not being able to connect to the emulator.

Here's an example failed execution on Travis:
https://travis-ci.org/CUTR-at-USF/android-maps-utils/builds/607898077

Here's the relevant log:

~~~
> Task :library:packageDebugAndroidTest UP-TO-DATE
[PropertyFetcher]: ShellCommandUnresponsiveException getting properties for device emulator-5554: null
10:35:39 V/ddms: execute: running getprop
10:35:41 V/ddms: execute: returning
10:35:41 W/PropertyFetcher: ShellCommandUnresponsiveException getting properties for device emulator-5554: null
> Task :library:connectedDebugAndroidTest
Skipping device 'test(AVD)' for 'library:': Unknown API Level
 > : No compatible devices connected.[TestRunner] FAILED 
Found 1 connected device(s), 0 of which were compatible.
10:35:41 I/XmlResultReporter: XML test result file generated at /home/travis/build/CUTR-at-USF/android-maps-utils/library/build/outputs/androidTest-results/connected/TEST-TestRunner-library-.xml. Total tests 1, failure 1, 
> Task :library:connectedDebugAndroidTest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':library:connectedDebugAndroidTest'.
> There were failing tests. See the report at: file:///home/travis/build/CUTR-at-USF/android-maps-utils/library/build/reports/androidTests/connected/index.html
* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':library:connectedDebugAndroidTest'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.GradleException: There were failing tests. See the report at: file:///home/travis/build/CUTR-at-USF/android-maps-utils/library/build/reports/androidTests/connected/index.html
	at com.android.build.gradle.internal.tasks.DeviceProviderInstrumentTestTask.doTaskAction(DeviceProviderInstrumentTestTask.java:226)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:51)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:31)
	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:91)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask.taskAction(NonIncrementalTask.kt:34)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
	... 34 more
* Get more help at https://help.gradle.org
BUILD FAILED in 49s
~~~

#### Environment details

master branch as of https://github.com/googlemaps/android-maps-utils/commit/a7ff535e7d81e137e34ac1b0d5e3b93b78100178 (after 0.6.2 release)

#### Steps to reproduce

  1. Make changes and open a PR to see a Travis build

### PR DESCRIPTION
**Pull request by barbeau**
To try and address #575, I'd like to try running API emulators 26, 27, and 28 on Travis in parallel to see if one fails more often than the others, and if they always all fail in lockstep or if the error seems more random with some passing and some failing for a given parallel build.

### CODE REVIEW

**Comment by barbeau** [comment]
Well:
* Good news - The builds across all 3 emulators are consistent
* Bad news - They are all stalling out during emulator startup with `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.` 🤦‍♂ 

Here's the link to all 3 builds for this PR:
https://travis-ci.org/googlemaps/android-maps-utils/builds/613583406

I'm restarting each of them individually to see if that makes any difference, but no luck so far. I'll keep investigating...

**Comment by jpoehnelt** [comment]
Thanks for the update.

**Comment by barbeau** [comment]
Even unchanged Travis configs are now having the same issue with the emulator startup timing out in other PRs:
* https://github.com/googlemaps/android-maps-utils/pull/586
* https://github.com/googlemaps/android-maps-utils/pull/587

So seems something changed with the emulator images or on Travis (?).

Here's a Travis build that is still working as of 7 hrs ago:
https://travis-ci.org/ankidroid/Anki-Android/builds/614021057

...and it's Travis config:
https://github.com/ankidroid/Anki-Android/blob/186e99f69208775f8036bb8694d5727c7f0212ab/.travis.yml

**Comment by barbeau** [comment]
https://github.com/ankidroid/Anki-Android/commit/5c6d293ebfb96d5ec56814bc2ae44209eb923caa says:

>To take advantage of some of the new nested virtualization capabilities
of some of the images in Travis, you must be using the newest LTS
release of Ubuntu, 18.04 Bionic Beaver.
>
>However, the Travis image of Bionic does not include support for JDK 8,
which we need to utilize the Android SDK manager. To circumvent this
issue, we change from the "android" language type to "generic", and take
care of both the JDK and the Android SDK ourselves.
>
>As such, this commit makes the following changes:
>* Switch `dist` from `trusty` to `bionic`
>* Switch `language` from `android` to `generic`
>* Enable the use of `sudo`
>* Install libpulse0 for emulator audio
>* Set up KVM inside the allocated Travis image
>* Use Gravis repository to download and install Java
>* Version android-wait-for-emulator in our repo
>* Download and install the Android SDK ourselves
>* Switch to `emulator-headless` for the x86 emulators
>
>Since we're free to switch Java versions as we please, we can finally
support JDK 11 by switching to it after starting our emulator.

**Comment by barbeau** [comment]
I've managed to change up the Travis config to get emulator builds working again - I'm not sure what happened, but the previous configuration just stopped working with emulators hanging on startup. I'm guessing it has to do with virtualization changes on Travis.

A few good things with the new config, which manually downloads and installs the JDK and Android SDK:
* Things run *much* faster - individual builds were previously around 13 minutes each, now they are running 7-8 minutes each (!)
* More emulators are now working - I've narrowed down the issue with `GradientTest.testInterpolateColor()` (see https://github.com/googlemaps/android-maps-utils/pull/573#issuecomment-556132522) and added code to conditionally run it on Android Oreo and higher (both locally and on CI). Plus more emulators actually run now on Travis. End result - a matrix with emulators 17-29 that work (see https://travis-ci.org/CUTR-at-USF/android-maps-utils/builds/614767635).

One exception - curiously, I'm seeing an `OutOfMemoryError` only with emulator 29 on the QuadTree tests that load up a bunch of items  (e.g., https://travis-ci.org/CUTR-at-USF/android-maps-utils/jobs/614767647):

~~~
11:00:57 V/InstrumentationResultParser: INSTRUMENTATION_STATUS_CODE: 1
11:01:00 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: class=com.google.maps.android.quadtree.PointQuadTreeTest
11:01:00 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: current=186
11:01:00 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
11:01:00 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: numtests=187
11:01:00 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: stack=java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
11:01:00 V/InstrumentationResultParser: 
11:01:00 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: stream=
11:01:00 V/InstrumentationResultParser: Error in testManyPoints(com.google.maps.android.quadtree.PointQuadTreeTest):
11:01:00 V/InstrumentationResultParser: java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
11:01:00 V/InstrumentationResultParser: 
11:01:00 V/InstrumentationResultParser: INSTRUMENTATION_STATUS: test=testManyPoints
com.google.maps.android.quadtree.PointQuadTreeTest > testManyPoints[test(AVD) - 10] FAILED 
java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw an exception; no stack trace available
~~~

I've bumped some of the Gradle memory requirements based on best practices:
* https://medium.com/google-developers/faster-android-studio-builds-with-dex-in-process-5988ed8aa37e
* https://medium.com/@wasyl/make-your-gradle-builds-fast-again-ea323ce6a435

...but I'm still seeing the problem.

I'm going to see if I can get the API 29 emulator too by tweaking the unit test itself - I noticed that some of the tests aren't clearing the tree at the end.

**Comment by jpoehnelt** [comment]
:tada:

**Comment by barbeau** [comment]
Optimizing the `PointQuadTreeTest.testManyPoints()` test didn't fix the problem, so I've added additional configuration to skip this particular test on the API 29 emulator when running on Travis.

So, in summary, we now have a matrix of API 17-29 emulators passing on Travis! :tada: 

I'm going to leave the entire matrix running for now in case we continue to have issues so it's easier to see if it's specific to an emulator or generally across Travis builds.

Ready for your review @jpoehnelt!

**Pull request merged**
