### PR TITLE
Remove noise from build

### PR DESCRIPTION
**Pull request by hannesa2**
Thank you for opening a Pull Request!

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)
- [ ] Will this cause breaking changes to existing Java or Kotlin integrations? If so, ensure the commit has a `BREAKING CHANGE` footer so when this change is integrated a major version update is triggered. See: https://www.conventionalcommits.org/en/v1.0.0/

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by arriolac** [comment]
Thanks for the PR! Can you provide more context in the description of the PR why the following lines could be removed?

**Comment by hannesa2** [comment]
image

Some commit messages speaks for itself, so explanation is often redundant.
* BuildTools are obsolete. Since > year always the latest (installed) is taken
* Java8 is now the default
* Kotlin jdk8 is a simple library update

**Review by arriolac — APPROVED** [review]
LGTM! Looks like there are some conflicts before I can merge.

**Comment by hannesa2** [comment]
rebase and solving conflicts are done

**Pull request merged**
