### PR TITLE
Heatmap with more than 1000 points

### PR DESCRIPTION
**Pull request by xni06**
These changes seek to address the issue when more than 1000 points (coordinates) are used in the heat map.

https://github.com/googlemaps/android-maps-utils/issues/71
http://stackoverflow.com/a/26143688

### CODE REVIEW

**Comment by xni06** [comment]
So, if you've a dataset that has more than 1,000 points and you'd like to make use of this new feature, the minimum that you'll need to do is call...
```
HeatmapTileProvider.Builder().pointsThreshold(HeatmapTileProvider.DEFAULT_POINTS_THRESHOLD)
```
or in full...
```
HeatmapTileProvider provider = new HeatmapTileProvider.Builder()
    .pointsThreshold(HeatmapTileProvider.DEFAULT_POINTS_THRESHOLD)
    .maxValue(HeatmapTileProvider.DEFAULT_MAX_VALUE) // optional
    .data(mCoordinates)
    .build();
```
My dataset only contains 5,000 points so I'd imagine that a smaller maxValue will need to be passed into the Builder should a larger dataset be used. It's not an ideal fix but it gives me a more realistic heat map to work with.

**Comment by xni06** [comment]
So, what was wrong with the build as it worked locally :-(

```
Caused by: com.android.ddmlib.InstallException: Unable to upload some APKs
```

**Comment by barbeau** [comment]
@xni06 If this PR passed the unit tests locally, most likely nothing is wrong with your PR - it failed on Travis due to a timeout (`com.android.ddmlib.ShellCommandUnresponsiveException`) when trying to run the unit tests on the emulator.  See http://stackoverflow.com/a/28949723/937715 for details.

Most likely, if the Travis build was restarted it will pass.  Unfortunately only repo admins have the ability to restart the Travis build.

**Comment by gwilyr01** [comment]
Thanks @barbeau . @broady or @markmcd could you rerun this build on Travis? Thanks

**Comment by markmcd** [comment]
I'm not entirely sure what the problem is that this pull request is solving. The issue you quoted (#71) was resolved in 57201be4b2733d45f1cf3143af3b9d8c8a6d3104.

I just whipped up a sample app myself with >1000 points and it seems to be working as expected. If you've got a case that is still failing, can you lodge a new issue that describes the problem?

**Comment by xni06** [comment]
With regards to #71, only the first part of the question was resolved - this resolves the missing second part...

https://github.com/googlemaps/android-maps-utils/issues/71#issuecomment-39816051

**Pull request closed without merging**
