### PR TITLE
Fix #519 - PolyUtil.distanceToLine() result

### LINKED ISSUE #519: PolyUtil.distanceToLine() producing incorrect result
**Summary:** 

PolyUtil.distanceToLine() produces wrong results in some cases

**Steps to reproduce:** 

PolyUtil.distanceToLine(
LatLng(13.384526409208775, 52.498523596997146),
LatLng(13.383257, 52.498945),
LatLng(13.383194, 52.498748)
) ~= 148m

**Expected behavior:** 

The correct result is somewhere between 93 and 97m

**Observed behavior:** 

The returned result is way incorrect.

If I change the point slightly, like let's say
LatLng(13.384605534374716, 52.49860503682293) it will return the correct result of about 98-99m

**Device and Android version:** 

Running on an Android 9 emulator

**Screenshots:** 

N/A

### PR DESCRIPTION
**Pull request by pauminku**
`PolyUtil.distanceToLine()` was not correct. Added a test to prove it.
Method and related tests corrected.

### CODE REVIEW

**Comment by pauminku** [comment]
It seems travis fails because the emulator doesn't respond, please consider review the pull request regardless of that

**Comment by barbeau** [comment]
This may fix https://github.com/googlemaps/android-maps-utils/issues/519

**Comment by jpoehnelt** [comment]
@googlebot

**Comment by barbeau** [comment]
@pauminku Looks like this has a few conflicts, would you be able to resolve?

**Comment by pauminku** [comment]
@barbeau I've merged all changes from origin's master and solved the conflict. There're a lot of changes on this merge (more than 2 years), but the pull request is for only 2 files (1 model class and 1 test class).

**Comment by barbeau** [comment]
Thanks @pauminku!

**Comment by pauminku** [comment]
@barbeau you are welcome. Thanks for reviewing the PR.

**Pull request merged**
