### PR TITLE
Made GeoJsonParser with parseGeometry public to use parser standalone

### PR DESCRIPTION
**Pull request by P72B**
As a user of the android-maps-utils lib I want to use the geoJson parser standalone to be able of parsing any kind of valid geoJson data with the lib.

### CODE REVIEW

**Comment by P72B** [comment]
As an example I whant to be able to achive this kind of processing:

Imagine there is a plain json server response like this
```
{
    "departures": [
        {
            "time": "2018-12-07T14:08:00+01:00",
            "route": {
                "name": "66",
                ...
            },
            "station": {
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                        48.8521614074707,
                        2.3397061824798584
                    ]
                },
                "name": "THE STATION NAME"
            }
        }, ...
    ], ...
}
```

The server response object contains a Station
```
data class Station(
        @SerializedName("name") val name: String?,
        @SerializedName("geometry") val geoJsonGeometry: Any?
) {
    fun getGeometry(): Geometry<Any>? = GeoJsonParser.parseGeometry(JSONObject(Gson().toJson(geoJson))) ?: null
}
```

**Comment by jpoehnelt** [comment]
@googlebot

**Comment by P72B** [comment]
> @P72B Thanks for the contribution! This looks good to me, but has a conflict. Could you please resolve the conflict and we can get this merged?

The issues are resolved and the branch is on top of upstream master. Feel free to merge and thx for the review @barbeau

**Comment by barbeau** [comment]
Thanks @P72B!

**Comment by Matungos** [comment]
@jpoehnelt 
Please make a release with this change included.

**Pull request merged**
