### PR TITLE
Update GeoJson demo to also include a local resource example.

### PR DESCRIPTION
**Pull request by stephenmcd**
In the GeoJson demo, adds a commented out call to demoing a local resource file (consistent with the KML demo now).

@markmcd PTAL

### CODE REVIEW

**Comment by markmcd** [comment]
Can you either rebase after the null check change goes in, or remove it from this change? I'm afk atm, will review properly a bit later.

**Comment by markmcd** [comment]
Other than the two files that seem to contain unrelated changes (rebase required?) - LGTM

**Comment by stephenmcd** [comment]
All up to date now

**Comment by markmcd** [comment]
:+1:

**Pull request merged**
