### PR TITLE
Gradle version bump + updated KML URL for demo.

### PR DESCRIPTION
**Pull request by stephenmcd**
@markmcd PTAL

### CODE REVIEW

**Comment by markmcd** [comment]
LGTM - though it looks like Travis is going to fail when you next merge, so I'd get a fix ready for that before merging this in. Gotta keep that front-page badge green :)

**Comment by barbeau** [comment]
Looks like there are a few things going on with Travis - I have a branch [here](https://github.com/barbeau/android-maps-utils/commits/fixTravis) that should work (container-based execution should be turned off due to memory issues), but it's still failing:
https://travis-ci.org/barbeau/android-maps-utils/builds/134484281

It looks like there was an Android SDK Tools version with a Google APIS emulator that was missing the ABIs - `24.0.2` is what Travis is using, and doing `android list targets` on Travis shows:

~~~
id: 10 or "Google Inc.:Google APIs:23"
     Name: Google APIs
     Type: Add-On
     Vendor: Google Inc.
     Revision: 1
     Description: Android + Google APIs
     Based on Android 6.0 (API level 23)
     Libraries:
      * com.google.android.media.effects (effects.jar)
          Collection of video effects
      * com.android.future.usb.accessory (usb.jar)
          API for USB Accessories
      * com.google.android.maps (maps.jar)
          API for Google Maps
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, WXGA720, WXGA800, WXGA800-7in
 Tag/ABIs : no ABIs.
~~~

`android list targets` on my machine with Android SDK Tools `25.1.7` correctly shows the ABIs:

~~~
id: 27 or "Google Inc.:Google APIs:23"
     Name: Google APIs
     Type: Add-On
     Vendor: Google Inc.
     Revision: 1
     Description: Android + Google APIs
     Based on Android 6.0 (API level 23)
     Libraries:
      * com.android.future.usb.accessory (usb.jar)
          API for USB Accessories
      * com.google.android.media.effects (effects.jar)
          Collection of video effects
      * com.google.android.maps (maps.jar)
          API for Google Maps
     Skins: HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800 (default), WVGA854, W
XGA720, WXGA800, WXGA800-7in
 Tag/ABIs : google_apis/armeabi-v7a, google_apis/x86, google_apis/x86_64
~~~

I don't believe there is a way to force a newer version of SDK Tools on Travis from our `.travis.yml` script, so I believe we just have to wait for their images to catch up.

**Comment by barbeau** [comment]
Just opened https://github.com/googlemaps/android-maps-utils/issues/284 for the Travis-specific issue - I'll post more updates there.

**Comment by stephenmcd** [comment]
Thanks a lot @barbeau - I guess we'll just wait :-)

**Pull request merged**
