### PR TITLE
Update the whole project including gradle, sdk, dependency actions etc

### PR DESCRIPTION
**Pull request by XinyueZ**
The project cannot be built after people check out directly, please merge this PR for development upgrade.

### CODE REVIEW

**Comment by barbeau** [comment]
@XinyueZ What version of Android Studio are you using?

**Comment by XinyueZ** [comment]
@barbeau I am using 3.3 and 3.2 both. That means gradle 3.3.0-alphaX or 3.2.0-rc0X

**Comment by XinyueZ** [comment]
Does anybody take care of this pr in order to ease 3rd developers in the future?

**Comment by friederbluemle** [comment]
And since the commit won't all build individually anyway, it would be a good idea to squash all or most of them. :bow:

**Comment by solcott** [comment]
Looks like the demo module needs to be updated too.

**Comment by amuramoto** [comment]
This was updated in a more recent commit. Apologies for the slow response on this PR!

**Pull request closed without merging**
