### PR TITLE
Move tests to JVM where possible.

### PR DESCRIPTION
**Pull request by arturdryomov**
Unfortunately tests using `org.json`, `org.xmlpull` and `android.graphics.Color` remain instrumented. It is possible to provide JSON and XML dependencies and offload even more tests to JVM but it feels like cheating since it is unknown which versions are bundled in the Android framework. A better approach would be unbundle from Android and use own JSON and XML dependencies.

At this point 99 tests are instrumented, 88 are on JVM.

### CODE REVIEW

**Comment by barbeau** [comment]
@arturdryomov Thanks for working on this! I agree that trying to move tests off the emulators when possible (and while it still matches the code an app running on Android would actually use) is a good thing.

You probably noticed that the emulators on Travis are broken yet again - it appears that the Android SDK team broke something in the latest emulator images:
https://issuetracker.google.com/issues/145622251

I opened an issue on this repo whose maintainer has been working extensively on Travis builds here, and he's working on a workaround:
https://github.com/ankidroid/Anki-Android/issues/5649

**Comment by arturdryomov** [comment]
@barbeau, an another option is Robolectric. I usually avoid it but it is still better than fighting emulators — this is a war which no one actually wins.

**Comment by jpoehnelt** [comment]
Could also do something like https://www.browserstack.com. Might be worth delaying some of these decisions until next year as we have another DPE starting that will be focusing on Android and iOS.

**Comment by barbeau** [comment]
@jpoehnelt Sounds good. I propose that we review/merge this PR, but hold off on further architectural changes for tests that currently depend on an emulator until later.

**Comment by jpoehnelt** [comment]
>I propose that we review/merge this PR, but hold off on further architectural changes for tests that currently depend on an emulator until later.

Agreed

**Comment by barbeau** [comment]
Closing and re-opening to trigger Travis again.

**Comment by arturdryomov** [comment]
@barbeau, hey, so what do we do with this? I can attempt to rebase it or close if it’s no longer relevant.

**Comment by barbeau** [comment]
@arturdryomov Sorry, I meant to follow up on this. Would you mind rebasing? I was waiting to merge this due to the file move until a few other PRs were merged.

**Comment by arturdryomov** [comment]
@barbeau, rebased and CI is green.

**Pull request merged**
