### PR TITLE
chore: Update v3 demo to match gms demo

### PR DESCRIPTION
**Pull request by barbeau**
Looks like the v3 variant demo had gotten out of sync with the gms variant demo.

This PR is the output of running:
* generateV3
* generateV3Layout

...which is a bunch of formatting and whitespace changes.

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)
- [x] Will this cause breaking changes to existing Java or Kotlin integrations? If so, ensure the commit has a `BREAKING CHANGE` footer so when this change is integrated a major version update is triggered. See: https://www.conventionalcommits.org/en/v1.0.0/

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by AndreasBoehm** [comment]
@barbeau It looks like you missed to commit the result of running `generateV3Layout`.
When I run it I have a couple of changed files:

```
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   demo/src/v3/res/layout/distance_demo.xml
	modified:   demo/src/v3/res/layout/geojson_demo.xml
	modified:   demo/src/v3/res/layout/heatmaps_demo.xml
	modified:   demo/src/v3/res/layout/kml_demo.xml
	modified:   demo/src/v3/res/layout/main.xml
	modified:   demo/src/v3/res/layout/map.xml
	modified:   demo/src/v3/res/layout/multi_profile.xml
	modified:   demo/src/v3/res/layout/places_demo.xml
```

**Comment by barbeau** [comment]
@AndreasBoehm Ah, good catch. I apparently had the "Reformat code" button checked within Android Studio when I created the first commit, and Android Studio removed the layout white space changes before committing. I've fixed this and pushed the changes in https://github.com/googlemaps/android-maps-utils/pull/896/commits/7a578ae8d49982f373445883a8d9f1c234faff34.

**Review by arriolac — APPROVED** [review]

**Comment by vikas0** [comment]
Does map saves its previous state in case of   savedInstanceState is not null in oncreate
    
 @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mIsRestore = savedInstanceState != null;
        setContentView(getLayoutId());
     
    }    
    

protected void startDemo(boolean isRestore) {
        if (!isRestore) {
            getMap().moveCamera(CameraUpdateFactory.newLatLng(new LatLng(31.4118,-103.5355)));
        }
        // Download the GeoJSON file.
        retrieveFileFromUrl();
        // Alternate approach of loading a local GeoJSON file.
        //retrieveFileFromResource();
    }

**Comment by barbeau** [comment]
@vikas0 Could you please open up a new issue for this? It would help focus the discussion.

**Pull request merged**
