### PR TITLE
fix: Remove Gradle configureondemand

### LINKED ISSUE #800: Build fails with Android Gradle Plugin 4.1.0
#### Summary

After updating from `classpath 'com.android.tools.build:gradle:4.0.2'` to `classpath 'com.android.tools.build:gradle:4.1.0'`, the demo app will no longer build and I get the error:

```
> Extension not initialized yet, couldn't access compileSdkVersion.
```

If I change back to `classpath 'com.android.tools.build:gradle:4.0.2'` it builds and runs without any problems.

Here's a branch showing the issue:

https://github.com/googlemaps/android-maps-utils/tree/sean/gradle-4.1.0

I believe this is an issue with Android Gradle Plugin 4.1.0, so I've opened an issue on the Google IssueTracker here:
https://issuetracker.google.com/issues/172273529

#### Expected behavior

Demo app should build (and from within Android Studio, the demo app should launch)

#### Observed behavior

```
Executing tasks: [:demo:assembleDebug] in project C:\android-projects\android-maps-utils

Starting Gradle Daemon...
Gradle Daemon started in 2 s 668 ms
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':demo:compileDebugJavaWithJavac'.
> Extension not initialized yet, couldn't access compileSdkVersion.
```

####  Steps to reproduce

1. Clone/checkout https://github.com/googlemaps/android-maps-utils/tree/sean/gradle-4.1.0
1. Run the `demo` app from within Android Studio, or run `./gradlew :demo:assembleDebug` from the command line

#### Environment details

See branch https://github.com/googlemaps/android-maps-utils/tree/sean/gradle-4.1.0 for code.

Build: AI-201.8743.12.41.6858069, 202009231536, 

AI-201.8743.12.41.6858069, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1536x960, 1707x960, 1536x864

AS: 4.1; Kotlin plugin: 1.4.10-release-Studio4.1-1; Android Gradle Plugin: 4.1.0; Gradle: 6.5; NDK: from local.properties: (not specified), latest from SDK: (not found); LLDB: pinned revision 3.1 not found, latest from SDK: (package not found); CMake: from local.properties: (not specified), latest from SDK: (not found), from PATH: (not found)

### PR DESCRIPTION
**Pull request by barbeau**
This is Option 1 to fix https://github.com/googlemaps/android-maps-utils/issues/800 as mentioned in https://github.com/googlemaps/android-maps-utils/issues/800#issuecomment-732239657.

Option 2 is presented in PR https://github.com/googlemaps/android-maps-utils/pull/894.

@arriolac What are your thoughts on this vs. Option 2?

This is certainly a simpler fix that keeps the old configuration, but the potential downside is reduced performance. I don't know what the real-world impact on this project is.

Only one of these two PRs should be merged.

---

Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open a GitHub issue as a bug/feature request before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)
- [x] Will this cause breaking changes to existing Java or Kotlin integrations? If so, ensure the commit has a `BREAKING CHANGE` footer so when this change is integrated a major version update is triggered. See: https://www.conventionalcommits.org/en/v1.0.0/

Fixes #800 🦕

### CODE REVIEW

**Review by arriolac — COMMENTED** [review]
I'd prefer this fix given its simplicity. But for thoroughness, I'm curious how much this affects performance. Perhaps it might be good to run the following and compare execution speeds `./gradlew library:assembleDebug`? Given that this project is fairly small already I imagine the deltas would be small.

**Comment by barbeau** [comment]
>Perhaps it might be good to run the following and compare execution speeds ./gradlew library:assembleDebug? Given that this project is fairly small already I imagine the deltas would be small.

I ran `./gradlew clean`, then closed the terminal, re-opened it, and ran `./gradlew library:assembleDebug` three times for each configuration.

You're right, the difference in build time looks negligible:

| Before (s) | After (s) |
| --- | --- |
| 5 | 7 |
| 6 | 6
| 5 | 6

**Comment by barbeau** [comment]
@arriolac This is ready for review when you have a chance

**Review by arriolac — APPROVED** [review]
LGTM!

**Pull request merged**
