### PR TITLE
Add containsLocation method to KmlGeometry and Placemark classes.

### PR DESCRIPTION
**Pull request by homaralex**
Convenience methods for checking whether a given location is inside a geometry or placemark object,
using the PolyUtil.containsLocation method.

### CODE REVIEW

**Comment by homaralex** [comment]
I signed it!

**Comment by broady** [comment]
This doesn't really make sense for lines or points. What is the motivation behind adding this?

**Comment by homaralex** [comment]
I needed a way to check inside, given a location, in which areas of a KML map does it lie - and then get Placemark info etc.
Maybe I was just missing a simpler way?

**Comment by broady** [comment]
That kind of code probably belongs *outside* these classes, I think. I can see something like `bool intersects(LatLngBounds)` being something generally applicable, though.

**Comment by homaralex** [comment]
The `LatLngBounds` approach wasn't accurate enough for me.
But yes, maybe this could be in `PolyUtil` or somewhere in KML Containers.

**Pull request closed without merging**
