### PR TITLE
Update Android Gradle plugin to 3.6.2

### PR DESCRIPTION
**Pull request by friederbluemle**
Android Studio 3.6.2 is now available:

https://androidstudio.googleblog.com/2020/03/android-studio-362-available.html

### CODE REVIEW

**Comment by barbeau** [comment]
Thanks @friederbluemle!  Looks like with this change, though, the project can't be opened in Android Studio 3.5. My preference would be to wait and let Android Studio 3.6 settle a bit before committing to it - especially because there seems to be a regression that breaks Git push again:
https://issuetracker.google.com/issues/124680708#comment15

**Comment by friederbluemle** [comment]
Thanks for your comment @barbeau - Makes sense. I don't personally do Git push operations from the IDE, but the issue you mentioned apparently has been fixed in 3.6.1:
https://androidstudio.googleblog.com/2020/02/android-studio-361-available.html
I'll keep this branch rebased until you feel comfortable to merge it.

**Comment by friederbluemle** [comment]
Rebased and updated to `3.6.2`.

**Comment by barbeau** [comment]
Thanks @friederbluemle! I'm going to close and re-open this to try and nudge Travis into reporting the status...

**Comment by friederbluemle** [comment]
Thanks @barbeau - Looks like the build on Travis CI got kicked off and was successful: https://travis-ci.org/github/googlemaps/android-maps-utils/builds/670187100
So webhooks are set up:
image

But the status did not get reported back: `Expected — Waiting for status to be reported`.
Maybe Travis needs to be re-authenticated?
I'll try to `git commit --amend --no-edit` and force push to give it another shot.

**Comment by barbeau** [comment]
@friederbluemle Yeah, I'm not sure what's going on - GitHub just doesn't seem to be getting the reported result from Travis. I'm seeing this on other newer PRs too - for example, https://github.com/googlemaps/android-maps-utils/pull/679.

**Pull request merged**
