### PR TITLE
Add Github issue and pull request templates

### PR DESCRIPTION
**Pull request by barbeau**
See https://github.com/blog/2111-issue-and-pull-request-templates for how these work with Github.  It's similar to how the AOSP issue tracker injects template text when you open a new issue.

I've found that these templates result in better formatted issues and pull requests from outside contributors in projects I've worked on, and also force me to better document bug reports/PRs myself as a maintainer - having the template to drop text into streamlines the process significantly.

If there is anything here you don't want (e.g., squashing commits) or something missing, let me know and I'd be happy to update the PR.

### CODE REVIEW

**Comment by broady** [comment]
Well, I think it'd be better to get CLA checking via GitHub status checks.

I'm not sure why that doesn't happen...

I just changed the settings for the repo to enforce squashes (disabling merge commits).

So I don't think the PR template is necessary.

**Comment by barbeau** [comment]
>Well, I think it'd be better to get CLA checking via GitHub status checks.

Agreed, I'm definitely not advocating that the PR template replaces the CLA bot (I've actually wanted to implement a CLA bot on my own repos, but haven't had the time to pull that together).

I think it would help cut back on some notification chatter, though, because if the contributor fills out the CLA prior to submitting the PR, the bot doesn't have to poke them, and they respond.  I'm fine removing the PR template, though - I'll force push another commit shortly with just the issue template.

**Comment by barbeau** [comment]
Ok, just force-pushed a new commit with just the issue template.

**Comment by broady** [comment]
CLA bot is now on this repo (added it 20 mins ago :)

**Comment by broady** [comment]
will leave to @stephenmcd to review this.

**Pull request merged**
